<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StartupObject>PBMAdjudicationService.Program</StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="PBMAdjudicationService.Worker\**" />
		<Content Remove="PBMAdjudicationService.Worker\**" />
		<EmbeddedResource Remove="PBMAdjudicationService.Worker\**" />
		<None Remove="PBMAdjudicationService.Worker\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Temporalio" Version="1.10.0" />
		<PackageReference Include="Temporalio.Extensions.Hosting" Version="1.10.0" />
	</ItemGroup>
</Project>